name: Node.js CI and Deploy to cPanel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: 🚚 Checkout Backend Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # Use sparse checkout to only include the backend directory
    - name: Enable Sparse Checkout
      run: |
        git config core.sparseCheckout true
        echo "backend/*" >> .git/info/sparse-checkout
        git read-tree HEAD  # Removed the '-u' option

    # List files to confirm the correct files are checked out
    - name: List Files After Sparse Checkout
      run: ls -R

    # Use the matrix node version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies in the backend directory
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: 🚚 Checkout Backend Code for Deployment
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # Use sparse checkout to only include the backend directory for deployment
    - name: Enable Sparse Checkout for Deployment
      run: |
        git config core.sparseCheckout true
        echo "backend/*" >> .git/info/sparse-checkout
        git read-tree HEAD  # Removed the '-u' option

    # List files to confirm the correct files are checked out for deployment
    - name: List Files After Sparse Checkout for Deployment
      run: ls -R

    # Use the latest Node.js version for deployment
    - name: Use Node.js 20.x for deployment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Install dependencies in the backend directory for deployment
    - name: Install Dependencies for Deploy
      run: npm ci
      working-directory: ./backend  # Ensure the working directory is set to 'backend'

    # Set environment variables
    - name: Set environment variables
      run: echo "Environment variables set"
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}        # Use GitHub Secrets for sensitive data
        PORT: ${{ secrets.PORT }}
        NODE_ENV: production

    # Deploy to cPanel using FTP
    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}      # Use GitHub Secrets for sensitive data
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend          # Set the backend directory for deployment
        server-dir: /music_app_API    # Replace with the directory on your cPanel server
